apiVersion: v1
kind: Service
metadata:
  name: aws-devops-demo
  labels:
    app: aws-devops-demo
spec:
  type: LoadBalancer          # Provisions an AWS ALB automatically
  selector:
    app: aws-devops-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws-devops-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-devops-demo
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
